-- Paste these entries into ox_inventory/data/items.lua.

['bandage'] = { label = 'Bandage', weight = 100, stack = true, close = true, description = 'Basic dressing for minor bleeding.' },
['med_gloves'] = { label = 'Medical Gloves', weight = 50, stack = true, close = true, description = 'Disposable gloves for patient care.' },
['med_gauze'] = { label = 'Medical Gauze', weight = 100, stack = true, close = true, description = 'Sterile gauze for wound packing.' },
['hemostatic_gauze'] = { label = 'Hemostatic Gauze', weight = 120, stack = true, close = true, description = 'Advanced gauze that helps control severe bleeding.' },
['tourniquet'] = { label = 'Tourniquet', weight = 150, stack = true, close = true, description = 'Used to control severe extremity bleeding.' },
['pressure_dressing'] = { label = 'Pressure Dressing', weight = 140, stack = true, close = true, description = 'Dressing used to apply pressure to bleeding wounds.' },
['chest_seal'] = { label = 'Chest Seal', weight = 100, stack = true, close = true, description = 'Occlusive dressing for penetrating chest trauma.' },
['splint'] = { label = 'Splint', weight = 500, stack = true, close = true, description = 'Stabilizes suspected fractures and sprains.' },
['neck_brace'] = { label = 'Neck Brace', weight = 450, stack = true, close = true, description = 'Supports cervical spine stabilization.' },
['backboard'] = { label = 'Backboard', weight = 2500, stack = true, close = true, description = 'Patient immobilization board.' },
['burn_dressing'] = { label = 'Burn Dressing', weight = 160, stack = true, close = true, description = 'Dressing for burns.' },
['oxygen_mask'] = { label = 'Oxygen Mask', weight = 300, stack = true, close = true, description = 'Mask used to provide supplemental oxygen.' },
['bvm'] = { label = 'BVM', weight = 700, stack = true, close = true, description = 'Bag valve mask for assisted ventilations.' },
['aed'] = { label = 'AED', weight = 1800, stack = false, close = true, description = 'Automated external defibrillator.' },
['defibrillator'] = { label = 'Defibrillator', weight = 2500, stack = false, close = true, description = 'Advanced cardiac defibrillator.' },
['iv_kit'] = { label = 'IV Kit', weight = 300, stack = true, close = true, description = 'Kit for starting an IV line.' },
['saline'] = { label = 'Saline Bag', weight = 700, stack = true, close = true, description = 'IV saline fluid.' },
['blood_bag'] = { label = 'Blood Bag', weight = 800, stack = true, close = true, description = 'Blood product for severe blood loss.' },
['pain_medication'] = { label = 'Pain Medication', weight = 80, stack = true, close = true, description = 'Medication for severe pain.' },
['epinephrine'] = { label = 'Epinephrine', weight = 80, stack = true, close = true, description = 'Emergency medication for shock or cardiac arrest.' },
['narcan'] = { label = 'Narcan', weight = 80, stack = true, close = true, description = 'Naloxone for suspected opioid overdose.' },
['trauma_kit'] = { label = 'Trauma Kit', weight = 1500, stack = true, close = true, description = 'Advanced trauma treatment kit.' },
